update data scheme for visualization
dyc3/senior-design pull request #249
Opened 2024-01-31 02:57 UTC by cjrkoa

2024-01-31 03:30 UTC, dyc3 requested changes
This is a severe regression in clarity. I didn't think there was any problem with this content the way it was.

I think you're going about this the wrong way. You need to determine how the data will get fed into grafana and how grafana will feed the data to the panels before you can refine this any further.

2024-01-31 03:30 UTC, dyc3 commented on visualization-design.typ
> +  color: Color,
Why is color determined here? This would be better to leave up to the renderer.

2024-01-31 03:30 UTC, dyc3 commented on visualization-design.typ
> +  parent: string,
Can `parent` not be derived? Why is it built in to the data?

2024-01-31 03:30 UTC, dyc3 commented on visualization-design.typ
> +Each balancer must have a state pictured below. The group property is not recieved from the balancer, but is one of the properties in json files read by D3.js:
> The group property

What is this?

> properties in json files read by D3.js

I'm confused -- this is supposed to be the format which is fed to the visualizations right? Why does it matter where it comes from?

2024-02-08 02:10 UTC, closed without merging

2024-02-08 02:10 UTC, cjrkoa commented
Will reopen something similar once #224 is complete